### ISSUE TITLE
Bot returns error when command is ran in new server

### ISSUE THREAD

**Issue by 4444dogs** [revoltchat/revolt.py#42]
**Describe the bug**
While a bot is online, if it joins a server and someone tries to run a command the bot returns an error.

**To Reproduce**
1. Run your Revolt bot.
2. Add it to a server
3. Try to run a command

```
Task exception was never retrieved
future: <Task finished name='Task-11' coro=<WebsocketHandler.handle_event() done, defined at %USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py:82> exception=KeyError('01G66YXP70EPXFFF0Q8RP9RBSW')>
Traceback (most recent call last):
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 94, in handle_event
    await func(payload)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 185, in handle_channelstarttyping       
    channel = self.state.get_channel(payload["id"])
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\state.py", line 45, in get_channel
    return self.channels[id]
KeyError: '01G66YXP70EPXFFF0Q8RP9RBSW'
Task exception was never retrieved
future: <Task finished name='Task-12' coro=<WebsocketHandler.handle_event() done, defined at %USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py:82> exception=KeyError('01G66YXP70EPXFFF0Q8RP9RBSW')>
Traceback (most recent call last):
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 94, in handle_event
    await func(payload)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 191, in handle_channelstoptyping        
    channel = self.state.get_channel(payload["id"])
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\state.py", line 45, in get_channel
    return self.channels[id]
KeyError: '01G66YXP70EPXFFF0Q8RP9RBSW'
Task exception was never retrieved
future: <Task finished name='Task-13' coro=<WebsocketHandler.handle_event() done, defined at %USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py:82> exception=KeyError('01G66YXP70EPXFFF0Q8RP9RBSW')>
Traceback (most recent call last):
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 94, in handle_event
    await func(payload)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 185, in handle_channelstarttyping       
    channel = self.state.get_channel(payload["id"])
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\state.py", line 45, in get_channel
    return self.channels[id]
KeyError: '01G66YXP70EPXFFF0Q8RP9RBSW'
Task exception was never retrieved
future: <Task finished name='Task-14' coro=<WebsocketHandler.handle_event() done, defined at %USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py:82> exception=KeyError('01G66YXP70EPXFFF0Q8RP9RBSW')>
Traceback (most recent call last):
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 94, in handle_event
    await func(payload)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 191, in handle_channelstoptyping        
    channel = self.state.get_channel(payload["id"])
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\state.py", line 45, in get_channel
    return self.channels[id]
KeyError: '01G66YXP70EPXFFF0Q8RP9RBSW'
Task exception was never retrieved
future: <Task finished name='Task-15' coro=<WebsocketHandler.handle_event() done, defined at %USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py:82> exception=KeyError('01G66YXP70EPXFFF0Q8RP9RBSW')>
Traceback (most recent call last):
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 94, in handle_event
    await func(payload)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 185, in handle_channelstarttyping       
    channel = self.state.get_channel(payload["id"])
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\state.py", line 45, in get_channel
    return self.channels[id]
KeyError: '01G66YXP70EPXFFF0Q8RP9RBSW'
Task exception was never retrieved
future: <Task finished name='Task-16' coro=<WebsocketHandler.handle_event() done, defined at %USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py:82> exception=KeyError('01FHGJ3NPP7XANQQH8C2BE44ZY')>
Traceback (most recent call last):
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 94, in handle_event
    await func(payload)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 267, in handle_userupdate
    user = self.state.get_user(payload["id"])
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\state.py", line 38, in get_user
    return self.users[id]
KeyError: '01FHGJ3NPP7XANQQH8C2BE44ZY'
Task exception was never retrieved
future: <Task finished name='Task-17' coro=<WebsocketHandler.handle_event() done, defined at %USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py:82> exception=KeyError('01G66YXP70EPXFFF0Q8RP9RBSW')>
Traceback (most recent call last):
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 94, in handle_event
    await func(payload)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 185, in handle_channelstarttyping       
    channel = self.state.get_channel(payload["id"])
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\state.py", line 45, in get_channel
    return self.channels[id]
KeyError: '01G66YXP70EPXFFF0Q8RP9RBSW'
Task exception was never retrieved
future: <Task finished name='Task-18' coro=<WebsocketHandler.handle_event() done, defined at %USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py:82> exception=KeyError('01G66YXP70EPXFFF0Q8RP9RBSW')>
Traceback (most recent call last):
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 94, in handle_event
    await func(payload)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 191, in handle_channelstoptyping        
    channel = self.state.get_channel(payload["id"])
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\state.py", line 45, in get_channel
    return self.channels[id]
KeyError: '01G66YXP70EPXFFF0Q8RP9RBSW'
Task exception was never retrieved
future: <Task finished name='Task-19' coro=<WebsocketHandler.handle_event() done, defined at %USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py:82> exception=KeyError('01G66YXP70EPXFFF0Q8RP9RBSW')>
Traceback (most recent call last):
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 94, in handle_event
    await func(payload)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 185, in handle_channelstarttyping       
    channel = self.state.get_channel(payload["id"])
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\state.py", line 45, in get_channel
    return self.channels[id]
KeyError: '01G66YXP70EPXFFF0Q8RP9RBSW'
Task exception was never retrieved
future: <Task finished name='Task-20' coro=<WebsocketHandler.handle_event() done, defined at %USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py:82> exception=KeyError('01G66YXP70EPXFFF0Q8RP9RBSW')>
Traceback (most recent call last):
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 94, in handle_event
    await func(payload)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 185, in handle_channelstarttyping       
    channel = self.state.get_channel(payload["id"])
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\state.py", line 45, in get_channel
    return self.channels[id]
KeyError: '01G66YXP70EPXFFF0Q8RP9RBSW'
Task exception was never retrieved
future: <Task finished name='Task-21' coro=<WebsocketHandler.handle_event() done, defined at %USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py:82> exception=KeyError('01G66YXP70EPXFFF0Q8RP9RBSW')>
Traceback (most recent call last):
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 94, in handle_event
    await func(payload)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 191, in handle_channelstoptyping        
    channel = self.state.get_channel(payload["id"])
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\state.py", line 45, in get_channel
    return self.channels[id]
KeyError: '01G66YXP70EPXFFF0Q8RP9RBSW'
Task exception was never retrieved
future: <Task finished name='Task-22' coro=<WebsocketHandler.handle_event() done, defined at %USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py:82> exception=KeyError('01G66YXP70EPXFFF0Q8RP9RBSW')>
Traceback (most recent call last):
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 94, in handle_event
    await func(payload)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 185, in handle_channelstarttyping       
    channel = self.state.get_channel(payload["id"])
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\state.py", line 45, in get_channel
    return self.channels[id]
KeyError: '01G66YXP70EPXFFF0Q8RP9RBSW'
Task exception was never retrieved
future: <Task finished name='Task-23' coro=<WebsocketHandler.handle_event() done, defined at %USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py:82> exception=KeyError('01G66YXP70EPXFFF0Q8RP9RBSW')>
Traceback (most recent call last):
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 94, in handle_event
    await func(payload)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 191, in handle_channelstoptyping        
    channel = self.state.get_channel(payload["id"])
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\state.py", line 45, in get_channel
    return self.channels[id]
KeyError: '01G66YXP70EPXFFF0Q8RP9RBSW'
Task exception was never retrieved
future: <Task finished name='Task-24' coro=<WebsocketHandler.handle_event() done, defined at %USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py:82> exception=KeyError('01G66YXP70EPXFFF0Q8RP9RBSW')>
Traceback (most recent call last):
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 94, in handle_event
    await func(payload)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\websocket.py", line 122, in handle_message
    message = self.state.add_message(cast(MessagePayload, payload))
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\state.py", line 73, in add_message
    message = Message(payload, self)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\message.py", line 62, in __init__
    channel = state.get_channel(data["channel"])
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\site-packages\revolt\state.py", line 45, in get_channel
    return self.channels[id]
KeyError: '01G66YXP70EPXFFF0Q8RP9RBSW'
```

**Expected behavior**
The bot should execute the command as usual.

**Library version**
```
Name: revolt.py
Version: 0.1.8
Summary: Python wrapper for the revolt.chat API
Home-page: https://github.com/revoltchat/revolt.py
Author: Zomatee
Author-email: me@zomatree.live
License: MIT
Location: c:\users\lee\appdata\local\programs\python\python310\lib\site-packages
Requires: aenum, aiohttp, typing-extensions, ulid-py
Required-by:
```

**Comment by 4444dogs** [comment]
Was fixed in 1ab91658c2a3b5e03d9fb363a244e903479a848c
