### ISSUE TITLE
AttributeError: module 'ulid' has no attribute 'new'

### ISSUE THREAD

**Issue by Motzumoto** [revoltchat/revolt.py#45]
```py
Traceback (most recent call last):
  File "/home/lain/.local/lib/python3.10/site-packages/revolt/ext/commands/command.py", line 73, in invoke
    return await self.callback(self.cog or context.client, context, *args, **kwargs)
  File "/mnt/c/Users/Lain/Desktop/Developer/revocat/cogs/test.py", line 9, in test
    await ctx.send("test")
  File "/home/lain/.local/lib/python3.10/site-packages/revolt/messageable.py", line 62, in send
    message = await self.state.http.send_message(await self._get_channel_id(), content, embed_payload, attachments, reply_payload, masquerade_payload)
  File "/home/lain/.local/lib/python3.10/site-packages/revolt/http.py", line 140, in send_message
    return await self.request("POST", f"/channels/{channel}/messages", json=json)
  File "/home/lain/.local/lib/python3.10/site-packages/revolt/http.py", line 68, in request
    json["nonce"] = ulid.new().str # type: ignore
AttributeError: module 'ulid' has no attribute 'new'
```

trying to use a command gives me this error

**Comment by Zomatree** [comment]
You have the wrong ulid library installed, make sure you have `ulid-py` installed.

**Comment by Motzumoto** [comment]
> You have the wrong ulid library installed, make sure you have `ulid-py` installed.

You'd think installing this lib would install the right one lmao

**Comment by Zomatree** [comment]
It does install the correct library, i dont know how you got the incorrect one.
