### ISSUE TITLE
User._update() does not update display_name changes (crash)

### ISSUE THREAD

**Issue by MysticMia** [revoltchat/revolt.py#56]
**Describe the bug**
I believe this error comes from a client event of someone hanging their username, and the bot trying to edit data in its cache.

```
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/revolt/websocket.py", line 113, in handle_event
    await func(payload)
  File "/home/container/.local/lib/python3.11/site-packages/revolt/websocket.py", line 378, in handle_userupdate
    user._update(**payload["data"])
TypeError: User._update() got an unexpected keyword argument 'display_name'
```

**To Reproduce**
Probably happens on any client..

**Expected behavior**
Expected no error (and the cache to be updated accordingly)

**Library version**
    0.1.11

**Comment by MysticMia** [comment]
Same seems to happen for `username`
