### ISSUE TITLE
Occasional Errors thrown for some reason?

### ISSUE THREAD

**Issue by Xynnix** [revoltchat/revolt.py#64]
**Describe the bug**
Lookup errors thrown on events I am not aware of using.
> ie: User Updates when a user updates their displayname in settings. 
![image](https://github.com/revoltchat/revolt.py/assets/53287573/e5601999-0d3d-412e-aafc-3bb9347d4e81)

**To Reproduce**:
```bash
Traceback (most recent call last):
  File "revolt\websocket.py", line 113, in handle_event
  File "revolt\websocket.py", line 378, in handle_userupdate
TypeError: User._update() got an unexpected keyword argument 'display_name'
Task exception was never retrieved
future: <Task finished name='Task-13845' coro=<WebsocketHandler.handle_event() done, defin
ed at revolt\websocket.py:102> exception=LookupError()>
Traceback (most recent call last):
  File "revolt\websocket.py", line 113, in handle_event
  File "revolt\websocket.py", line 147, in handle_message
  File "revolt\state.py", line 92, in add_message
  File "revolt\message.py", line 88, in __init__
  File "revolt\state.py", line 49, in get_member
  File "revolt\server.py", line 213, in get_member
LookupError
Task exception was never retrieved
future: <Task finished name='Task-14899' coro=<WebsocketHandler.handle_event() done, defin
ed at revolt\websocket.py:102> exception=TypeError("User._update() got an unexpected keywo
rd argument 'username'")>
Traceback (most recent call last):
  File "revolt\websocket.py", line 113, in handle_event
  File "revolt\websocket.py", line 378, in handle_userupdate
TypeError: User._update() got an unexpected keyword argument 'username'
Task exception was never retrieved
future: <Task finished name='Task-15658' coro=<WebsocketHandler.handle_event() done, defin
ed at revolt\websocket.py:102> exception=TypeError("User._update() got an unexpected keywo
rd argument 'username'")>
```
**Expected behavior**

**Screenshots**
![image](https://github.com/revoltchat/revolt.py/assets/53287573/d0f8354a-7d43-4ca3-83d1-39d06dc4255b)

**Library version**
Access this info via `pip show revolt.py`
![image](https://github.com/revoltchat/revolt.py/assets/53287573/9b20e363-55a6-4aa0-97ad-9048837579a6)

**Additional context**
Source Code:
> https://github.com/Akrasio/Ahni-Revolt/blob/revolt.py/index.py

**Comment by Zomatree** [comment]
This is already fixed on the master version.
